config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    collection do
      post 'upload'
    end
  end
  resources :shippings do
    member do
      get 'price'
      get 'details'
    end
    collection do
      get 'label'
      get 'manifest'
      get 'artifact'
    end
  end

  root 'welcome#index'
  post '/' => 'welcome#index'
  get 'token' => 'registration#token'
  get '/registration_callback' => 'registration#callback'

end

app/models/shipping.rb
class Shipping < ActiveRecord::Base
  has_many :links

  def self.track_shipping(response)
    shipping_info = response[:create_shipping]
    transmit_shipping = response[:transmit_shipping]
    shipment_info = shipping_info[:shipment_info]
    shipping = self.new(xmlns: shipment_info[:xmlns], shipment_id: shipment_info[:shipment_id],
                        shipment_status: shipment_info[:shipment_status], tracking_pin: shipment_info[:tracking_pin])
    if shipping.save
      links = shipment_info[:links][:link]
      links.each do |link|
        store_link(shipping, link)
      end
      if transmit_shipping[:manifests].present?
        link = transmit_shipping[:manifests][:link]
        store_link(shipping, link)
      end
    end
  end

  def self.store_link(shipping, link)
    shipping_link = shipping.links.build(rel: link[:rel], href: link[:href], media_type: link[:media_type])
    shipping_link.save
  end

  def get_url(type)
    label = links.where(rel: type).first
    if label.present?
      label.href
    end
  end

end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController
  before_action :set_shipping, only: [:show, :edit, :update, :destroy]

  # GET /shippings
  # GET /shippings.json
  def index
    puts @unknown.round(0)
    @shippings = Shipping.all
  end

  # GET /shippings/1
  # GET /shippings/1.json
  def show
  end

  # GET /shippings/new
  def new

  end

  # GET /shippings/1/edit
  def edit
  end

  def price
    shipping_id = params[:id] # Shipment ID
    @response = CANADA_POST_SERVICE.get_price(shipping_id)
  end

  def label
    label_url = params[:url] # Shipment ID
    response = CANADA_POST_SERVICE.get_label(label_url)
    send_data(response.body, filename: 'shipping_label.pdf')
  end

  def details
    shipping_id = params[:id] # Shipment ID
    @response = CANADA_POST_SERVICE.details(shipping_id)
  end

  def artifact
    url = params[:url]
    @response = CANADA_POST_SERVICE.get_artifact(url)
    unless @response[:errors].present?
      send_data(@response[:artifact].body, filename: 'shipping_artifact.pdf')
    end
  end

  def manifest
    url = params[:url]
    @response = CANADA_POST_SERVICE.get_manifest(url)
  end

  # POST /shippings
  # POST /shippings.json
  def create
    @sender = params[:sender]
    @destination = params[:destination]
    @package = params[:package]
    @notification = params[:notification]
    @preferences = params[:preferences]
    @settlement_info = params[:settlement_info]
    @request = {
      sender: @sender,
      destination: @destination,
      package: @package,
      notification: @notification,
      preferences: @preferences,
      settlement_info: @settlement_info,
      group_id: '5241556',
      mailing_date: Date.today,
      contract_number: '0042956527',
      service_code: params[:service_code],
      mobo: {
        customer_number: params[:mobo],
        username: 'bc02d6bd3733555c',
        password: '111d1a0d29fc00aa47b66a',
        contract_number: '0042956527'
      }
    }
    puts "**** #{@request}"

    @response = CANADA_POST_SERVICE.create(
        sender: @sender,
        destination: @destination,
        package: @package,
        notification: @notification,
        preferences: @preferences,
        settlement_info: @settlement_info,
        group_id: '5241556',
        mailing_date: Date.today,
        contract_id: '0042956527',
        service_code: params[:service_code],
        mobo: {
            customer_number: params[:mobo],
            username: 'bc02d6bd3733555c',
            password: '111d1a0d29fc00aa47b66a',
            contract_number: '0042956527'
        }
    )
    puts "Full Response: #{@response}"
    unless @response[:create_shipping][:errors].present?
      Shipping.track_shipping(@response)
    end
    respond_to do |format|
      format.js {}
    end
  end

  # PATCH/PUT /shippings/1
  # PATCH/PUT /shippings/1.json
  def update
    respond_to do |format|
      if @shipping.update(shipping_params)
        format.html { redirect_to @shipping, notice: 'Shipping was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipping }
      else
        format.html { render :edit }
        format.json { render json: @shipping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shippings/1
  # DELETE /shippings/1.json
  def destroy
    @shipping.destroy
    respond_to do |format|
      format.html { redirect_to shippings_url, notice: 'Shipping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_shipping
    @shipping = Shipping.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shipping_params
    params[:shipping]
  end
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/shippings/_form.html.erb
<div class="col-lg-12">
  <div class="col-lg-12">
    <div class="shipping-error"></div>
  </div>
</div>
<%= form_tag(shippings_path, remote: true) do %>

    <div class="col-lg-12">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading"> Service & Customer Settings</div>
          <div class="panel-body">
            <div class="col-lg-6">
              <%= select_tag('service_code', options_for_select(CanadaPost::Request::Shipping::SERVICE_CODES.collect { |key, value| [value, key] }), class: 'form-control') %>
            </div>
            <div class="col-lg-6">
              <%= text_field_tag('mobo', '', class: 'form-control', placeholder: 'Mail behind of') %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= render 'welcome/package_info' %>
    <%= render 'welcome/notification_and_preference' %>

    <div class="col-sm-12">
      <%= render 'welcome/sender_info' %>
      <%= render 'welcome/destination_info' %>
    </div>

    <div class="col-lg-12">
      <div class="form-group col-lg-12">
        <%= submit_tag('Create Shipment', class: 'btn btn-default pull-right') %>
        <%= image_tag('arrow-loader.gif', class: 'loader') %>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $(document).ajaxSend(function () {
            $('.loader').show();
        });
    });
</script>

app/views/shippings/_link.html.erb
<ul>
  <li><label> Type </label> : <%= link.rel %> </li>
  <li><label> Href </label> : <%= link.href %> </li>
  <li><label> Media Type </label> : <%= link.media_type %> </li>
</ul>

app/views/shippings/artifact.html.erb
<%= @response[:errors] %>

app/views/shippings/create.js.erb
if (<%= @response[:create_shipping][:errors].present? %>) {
    $('.shipping-error').removeClass('alert-success').addClass('alert alert-danger').html("<%= @response[:create_shipping][:errors] %>");
}
else {
    $('.shipping-error').removeClass('alert-danger').addClass('alert alert-success').html("Shipping has been created successfully");
}

$('.loader').hide();
$("html,body").scrollTop(0);

app/views/shippings/details.html.erb
<%= @response %>

app/views/shippings/edit.html.erb
<div class="col-lg-12">
  <h1>Editing Shipping</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @shipping %> |
<%= link_to 'Back', shippings_path %>

app/views/shippings/index.html.erb
<div class="col-lg-12">
  <p id="notice"><%= notice %></p>

  <h1>Listing Shippings</h1>

  <table class="table table-bordered">
    <thead>
    <tr>
      <th> ID</th>
      <th> Xmlns</th>
      <th> Shipment ID</th>
      <th> Shipment Status</th>
      <th> Tracking Pin</th>
      <th> Creation</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @shippings.each do |shipping| %>
        <tr>
          <td> <%= shipping.id %> </td>
          <td> <%= shipping.xmlns %> </td>
          <td> <%= shipping.shipment_id %> </td>
          <td> <%= shipping.shipment_status %> </td>
          <td> <%= shipping.tracking_pin %> </td>
          <td> <%= shipping.created_at %> </td>
          <td><%= link_to 'Show', shipping %></td>
          <td><%= link_to 'Edit', edit_shipping_path(shipping) %></td>
          <td><%= link_to 'Destroy', shipping, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Shipping', new_shipping_path %>
</div>

app/views/shippings/label.html.erb
<%= @response %>

app/views/shippings/manifest.html.erb
<%= @response %>

app/views/shippings/new.html.erb
<div class="col-lg-12">
  <h1 class="col-lg-12">New Shipping</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', shippings_path %>

app/views/shippings/price.html.erb
<%= @response.inspect %>

app/views/shippings/show.html.erb
<div class="col-lg-12">
  <h3> Shipment Information </h3>
  <ul>
    <li>
      <label> Xmlns </label>: <%= @shipping.xmlns %>
    </li>
    <li>
      <label> Shipment ID </label>: <%= @shipping.shipment_id %>
    </li>
    <li>
      <label> Status </label>: <%= @shipping.shipment_status %>
    </li>
    <li>
      <label> Tracking Pin </label>: <%= @shipping.tracking_pin %>
    </li>
    <li>
      <label> Creation </label>: <%= @shipping.created_at %>
    </li>
  </ul>

  <h3> Shipment Tracking Links </h3>

  <div class="panel panel-default">
    <div class="panel-heading"> Shipping Details</div>
    <div class="panel-body panel-success">
      <%= link_to('Get Shipping Price', price_shipping_path(@shipping.shipment_id), class: 'btn btn-warning') %>
      <%= link_to('Get Shipping Details', details_shipping_path(@shipping.shipment_id), class: 'btn btn-primary') %>
      <%= link_to('Get Shipping Label', label_shippings_path(url: @shipping.get_url('label')), class: 'btn btn-success') %>
      <%= link_to('Get Manifest', manifest_shippings_path(url: @shipping.get_url('manifest')), class: 'btn btn-success') %>
      <%= link_to('Get artifact', artifact_shippings_path(url: @shipping.get_url('manifest')), class: 'btn btn-success') %>
    </div>
  </div>
</div>

<!--<ul>-->
<%# @shipping.links.each do |link| %>
<!--<li>-->
<%#= render 'shippings/link', link: link %>
<!--</li>-->
<%# end %>
<!--</ul>-->