config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    collection do
      post 'upload'
    end
  end
  resources :shippings do
    member do
      get 'price'
      get 'details'
    end
    collection do
      get 'label'
      get 'manifest'
      get 'artifact'
    end
  end

  root 'welcome#index'
  post '/' => 'welcome#index'
  get 'token' => 'registration#token'
  get '/registration_callback' => 'registration#callback'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def upload
    unless params[:file0].nil?
      @uploader = PostUpload.new#.last#PostUpload.new
      @uploader.image = params[:file0]
      @uploader.save
    end
    puts @uploader.inspect
    respond_to do |format|
      format.js {}
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :image, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post_form.html.erb
<div class="container-fluid">
  <div class="panel panel-success">
    <div class="panel-heading"> New Comments </div>
    <div class="panel-body">
      <%= form_for @post do |f| %>
          <!--<div class="form-group">-->
            <!--<%#= f.label :title %>-->
            <!--<%#= f.text_field :title, class: 'form-control' %>-->
          <!--</div>-->
          <div class="form-group">
            <%= f.label :content, 'Comments' %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<ul>
  <% @posts.each do |post| %>
      <li>
        <!--<h4><%#= post.title %></h4>-->

        <div>
          <%= raw Markdown.new(post.content).to_html %>
        </div>
        <div class="actions">
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
      </li>
  <% end %>
</ul>

<br>

<%= render 'post_form' %>

<script type="text/javascript">
    $(function () {
        var dropzone = document.getElementById('post_content'); // paste your dropzone id here
        dropzone.ondragenter = function (e) {
            $('#post_content').addClass('drop-active');
        };

        dropzone.ondragover = function (e) {
            $('#post_content').addClass('drop-active');
        };

        dropzone.ondragleave = function (e) {
            $('#post_content').removeClass('drop-active');
        };

        dropzone.ondrop = function (e) {
            $('#post_content').removeClass('drop-active');
            e.preventDefault();  // stop default behaviour
            readfiles(e.dataTransfer.files); // function to handle file(s) that was added to dropzone
        };
    });

    function readfiles(files) {
        var formData = new FormData(); // we initialise a new form that will be send to php
        for (var i = 0; i < files.length; i++) {
            filename = files[i].name;
            ext = filename.split('.').pop();
            if ("jpg jpeg gif png".indexOf(ext) > -1) {
                formData.append('file' + i, files[i]);
            }
            else {
                alert("Only image allowed here");
                return false;
            }
        }
        //formData.append('moreInfo', 'myValuableValue');// you can append additional string info
        $.ajax({
            url: '<%= upload_posts_path %>',
            type: 'POST',
            data: formData,
            async: true,
            success: function (data) {

            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/upload.js.erb
<% if  @uploader.errors.present? %>
alert("Only Image allowed here");
<%else%>
content = $('#post_content').val();
content += "![<%= @uploader.image_identifier %>](<%= image_without_asw_params(@uploader.image_url) %>)";
$('#post_content').val(content);
<%end%>